//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AuctionId { get; set; }
        public System.DateTime DateTime { get; set; }
        public byte TypeBid { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Auction Auction { get; set; }
        public virtual User User { get; set; }
    }
}
